//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanTestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransferLogs
    {
        public long ID { get; set; }
        public long AssetID { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string FromAssetSN { get; set; }
        public string ToAssetSN { get; set; }
        public long FromDepartmentLocationID { get; set; }
        public long ToDepartmentLocationID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual DepartmentLocations DepartmentLocations { get; set; }
        public virtual DepartmentLocations DepartmentLocations1 { get; set; }
    }
}
